### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by wilfried18** [NikosSiak/AndroidftpClient#1]
Hi
Can you do an apk 
In order to use the application
Think about the ones who don't make it to apk.
Thank you

**Comment by NikosSiak** [comment]
Hello @wilfried18, this was a learning project it wasn't meant for release that's why there is no apk

**Comment by NikosSiak** [comment]
https://github.com/NikosSiak/AndroidftpClient/releases/tag/1.0.0

**Comment by wilfried18** [comment]
it's a good learning project, there's not enough open source FTP client under Android
